### ISSUE TITLE
exception occurred:"Failed to get reply: Broken pipe"

### ISSUE THREAD

**Issue by zhanghongg** [sewenew/redis-plus-plus#234] opened 2021-05-25 10:19 UTC
I try to request and using sentry mode:

OptionalString sObj = pRedis->command<OptionalString>("get",sCombineId);

This exception occurs, and the error does not seem to recover immediately (the connection pool does not reconnect the connection), and it can automatically reply after a period of time(about 30 minutes). What's the problem? How should I solve it?

I look forward to your reply.

**Comment by sewenew** [comment] 2021-05-25 14:09
Sorry, but I cannot reproduce the problem. I checked the code, if connection fails, it should reconnect automatically. I'm not sure if there's some problem with your Redis server. Can you check if that during this period (about 30 minutes), Redis server and sentinel are working correctly? If there's a failover happened, e.g. mater was down, and a slave was promoted?

Also please show me your code that can reproduce the problem. So that I can take a deep look into it.

Regards

**Comment by zhanghongg** [comment] 2021-05-26 01:47
There are some connections in close_wait. This indicates that the connection is closed by the redis service. When the service actively closes the client connection, will there be any problems with the connection pool's management of the connection?

**Comment by sewenew** [comment] 2021-05-26 14:51
You can try the following code to see if the connection has been reconnected:

```
while (true) {
    try {
        cout << redis.ping() << endl;
        this_thread::sleep_for(chrono::seconds(10));
    } catch (const Error &e) {
        cout << e.what() << endl;
    }
}
```

When the test is running, you can use redis-cli to log on Redis server, and use the `client list` command to get the ip and port info of the test program. Then call `client kill ip:port` to close the connection. You should see the test program print something like the following:

```
PONG
PONG
error info, since the connection is closed by server
PONG
```

As the result shows, redis-plus-plus will reconnect automatically, unless the server has some problem, and cannot be connected.

Regards

**Comment by sewenew** [comment] 2021-07-26 12:54
Since there's no update, I'll close the issue. If you still have problem, feel free to reopen it.

Regards

**Closed by sewenew** 2021-07-26 12:54 UTC

**Comment by zhanghongg** [comment] 2021-07-28 06:11
Sorry, I'm in trouble.
How do I ensure that every connection in the connection pool is alive ? 
In other words, how do I ensure that every command I give will succeed?

My initialization code:
                        SentinelOptions sentinel_opts;
                        sentinel_opts.nodes = {nodes};   // Required. List of Redis Sentinel nodes.
//                      sentinel_opts.password = password;
                        sentinel_opts.connect_timeout = std::chrono::milliseconds(10000);
                        sentinel_opts.socket_timeout = std::chrono::milliseconds(10000);
                        auto sentinel = std::make_shared<Sentinel>(sentinel_opts);

                        ConnectionOptions connection_opts;
                        connection_opts.password = password;  // Optional. No password by default.
                        connection_opts.connect_timeout = std::chrono::milliseconds(10000);   // Required.
                        connection_opts.socket_timeout = std::chrono::milliseconds(10000);    // Required.
                        connection_opts.db = dbnum;
                        connection_opts.keep_alive = true;

                        ConnectionPoolOptions pool_opts;
                        pool_opts.size = 100; // Optional. The default size is 1.
                        pool_opts.connection_lifetime = std::chrono::milliseconds(60000);

                        return std::make_shared<Redis>(sentinel, masterName, Role::MASTER, connection_opts, pool_opts);
My use case:
        while(true) {
                std::string c;
                printf("input g or q \n");
                cin>>c;
                if(c == "g") {
                        try {
                                OptionalString sObj = pRedis->command<OptionalString>("get",key);
                                if(sObj) {
                                        printf("get : %s\n", sObj.value().c_str());
                                }
                        }
                        catch(std::exception &e) {
                                printf("exception: %s\n", e.what());
                        }
                }
                if(c== "q") {
                        break;
                }
        }
Problems encountered:
When the interval between two calls is long:
Exception: Failed to get reply: Server closed the connection.


发件人: sewenew
发送时间: 2021年5月26日 22:51
收件人: sewenew/redis-plus-plus
抄送: zhanghongg; Author
主题: Re: [sewenew/redis-plus-plus] exception occurred:"Failed to getreply: Broken pipe" (#234)

You can try the following code to see if the connection has been reconnected:
while (true) {
    try {
        cout << redis.ping() << endl;
        this_thread::sleep_for(chrono::seconds(10));
    } catch (const Error &e) {
        cout << e.what() << endl;
    }
}
When the test is running, you can use redis-cli to log on Redis server, and use the client list command to get the ip and port info of the test program. Then call client kill ip:port to close the connection. You should see the test program print something like the following:
PONG
PONG
error info, since the connection is closed by server
PONG
As the result shows, redis-plus-plus will reconnect automatically, unless the server has some problem, and cannot be connected.
Regards

**Comment by sewenew** [comment] 2021-07-28 14:12
> In other words, how do I ensure that every command I give will succeed?

There's no guarantee that every command will be successful. If it fails, redis-plus-plus will throw and exception, i.e. `sw::redis::Error`. You can catch the exception, and try the command.

> Problems encountered:
> When the interval between two calls is long:
> Exception: Failed to get reply: Server closed the connection.

The error message shows that the server has closed the connection. You Redis server might configured the idle timeout. If you didn't send any command before the timeout reaches, the server will close the connection. In order to avoid the problem, you can reconfigure your server to disable the timeout, or send the `PING` command to Redis regularly.

Regrads

**Comment by zhanghongg** [comment] 2021-07-29 01:07
In order to avoid the problem, you can reconfigure your server to disable the timeout, or send the PING command to Redis regularly.

What should I do to ensure that every connection in the connection pool is PINGed？


发送自 Windows 10 版邮件应用

发件人: sewenew
发送时间: 2021年7月28日 22:12
收件人: sewenew/redis-plus-plus
抄送: zhanghongg; Author
主题: Re: [sewenew/redis-plus-plus] exception occurred:"Failed to getreply: Broken pipe" (#234)

In other words, how do I ensure that every command I give will succeed?
There's no guarantee that every command will be successful. If it fails, redis-plus-plus will throw and exception, i.e. sw::redis::Error. You can catch the exception, and try the command.
Problems encountered:
When the interval between two calls is long:
Exception: Failed to get reply: Server closed the connection.
The error message shows that the server has closed the connection. You Redis server might configured the idle timeout. If you didn't send any command before the timeout reaches, the server will close the connection. In order to avoid the problem, you can reconfigure your server to disable the timeout, or send the PING command to Redis regularly.
Regrads

**Comment by sewenew** [comment] 2021-07-29 15:01
I implement an easy solution. If the connection has been idle for a long time, redis-plus-plus will reconnect to it before seeing the command. Please checkout the latest code on dev branch to have a try.

With the latest code, you should set the `ConnectionPoolOptions::connection_idle_time` to a duration less than Redis server's timeout configuration. Say, if Redis is configured to close connection that has been idled for 10 minutes, you can set `connection_idle_time` to be 9 minutes.

```
pool_opts.connection_idle_time = std::chrono::minutes(1);   // should be less than the *timeout* configuration in redis.conf file.
```

Regards

**Comment by zhanghongg** [comment] 2021-08-02 06:43
The problem is solved. Thank you！！！！


发件人: sewenew
发送时间: 2021年7月29日 23:02
收件人: sewenew/redis-plus-plus
抄送: zhanghongg; Author
主题: Re: [sewenew/redis-plus-plus] exception occurred:"Failed to getreply: Broken pipe" (#234)

I implement an easy solution. If the connection has been idle for a long time, redis-plus-plus will reconnect to it before seeing the command. Please checkout the latest code on dev branch to have a try.
With the latest code, you should set the ConnectionPoolOptions::connection_idle_time to a duration less than Redis server's timeout configuration. Say, if Redis is configured to close connection that has been idled for 10 minutes, you can set connection_idle_time to be 9 minutes.
pool_opts.connection_idle_time = std::chrono::minutes(1);   // should be less than the *timeout* configuration in redis.conf file.
Regards
