### ISSUE TITLE
[BUG]  Compile error when building against Epics Base   ConnectionType does not name a type

### ISSUE THREAD

**Issue by bigsamich** [sewenew/redis-plus-plus#363] opened 2022-05-17 17:58 UTC
**Describe the bug**
Compile error. missing type definitions

<command-line>:0:6: error: expected identifier before numeric constant
<command-line>:0:6: error: expected '}' before numeric constant
<command-line>:0:6: error: expected unqualified-id before numeric constant
In file included from /usr/local/include/sw/redis++/connection_pool.h:26:0,
                 from /usr/local/include/sw/redis++/redis.h:25,
                 from /usr/local/include/sw/redis++/redis++.h:20,
                 from ../test.cpp:14:
/usr/local/include/sw/redis++/connection.h:56:5: error: 'ConnectionType' does not name a type
     ConnectionType type = ConnectionType::TCP;
     ^
/usr/local/include/sw/redis++/connection.h:76:5: error: 'tls' does not name a type
     tls::TlsOptions tls;
     ^
/usr/local/include/sw/redis++/connection.h:157:5: error: 'ReplyUPtr' does not name a type
     ReplyUPtr recv(bool handle_error_reply = true);
     ^
/usr/local/include/sw/redis++/connection.h:200:5: error: 'tls' does not name a type
     tls::TlsContextUPtr _tls_ctx;
     ^

**Environment:**
 - OS: Scientific Linux
 - Compiler: gcc (Red Hat 4.8.5-36)
 - hiredis version: 1.0.3

**Comment by sewenew** [comment] 2022-05-18 00:31
You can take a look at the installed connection.h file. It should contains the definition of `ConnectionType`.

Did you build your application code with `-std=c++11` or `-std=c++17` standard? Since redis-plus-plus only works with C++ 11 or later, you. must also build your application code with C++11 or higher version of C++ standard.

Regards

**Comment by bigsamich** [comment] 2022-05-18 01:06
Both were compiled with  -std=c++11

**Comment by sewenew** [comment] 2022-05-18 10:25
I cannot reproduce the problem on Centos7 gcc 4.8.5 with the latest redis-plus-plus. Can you try to reinstall redis-plus-plus to take a try? `rm -rf /usr/local/include/sw /usr/local/lib/libredis++.a/.so /usr/local/lib64/libredis++.a/.so` first.

Regards

**Comment by bigsamich** [comment] 2022-05-19 13:57
No luck. I have been able to recreate a similar problem when including ncurses.h in the same application but this time around errors.h. Both errors seem to imply issues around an enum.

 /usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE           -D_X86_64_  -DUNIX  -Dlinux      -O3   -Wall    -std=c++11 -g -DNETCOMMS_TRANSPORT=UDP -D_REENTRANT -fPIC -DLINUX -pipe -Wno-format-extra-args -Wno-literal-suffix  -mtune=generic      -m64  -I. -I../O.Common -I. -I. -I.. -I../../../include/compiler/gcc -I../../../include/os/Linux -I../../../include -I/usr/local/epics/base/include/compiler/gcc -I/usr/local/epics/base/include/os/Linux -I/usr/local/epics/base/include      -I/usr/local/epics/Support/acnetPV/include   -I/usr/local/epics/Support/alive/include  -I/usr/local/epics/Support/iocStats/include/os/Linux -I/usr/local/epics/Support/iocStats/include   -I/usr/local/epics/Support/calc/include   -I/usr/local/epics/Support/sscan/include           -I/usr/local/products/include    -c ../readBPM.cpp
 In file included from ../readBPM.cpp:8:0:
 /usr/local/include/sw/redis++/errors.h:29:5: error: expected identifier before '(' token
      ERR,
      ^
 /usr/local/include/sw/redis++/errors.h:29:5: error: expected '}' before '(' token
 /usr/local/include/sw/redis++/errors.h:29:5: error: expected unqualified-id before '-' token
      ERR,
      ^
 /usr/local/include/sw/redis++/errors.h:29:5: error: expected ')' before '-' token
 In file included from /usr/local/include/sw/redis++/connection.h:28:0,
                  from /usr/local/include/sw/redis++/connection_pool.h:26,
                  from /usr/local/include/sw/redis++/redis.h:25,
                  from /usr/local/include/sw/redis++/redis++.h:20,
                  from /usr/local/products/include/adinstDAQ/BIBPMClient.hpp:6,
                  from ../readBPM.cpp:19:
 /usr/local/include/sw/redis++/errors.h:164:1: error: expected declaration before '}' token
  }
  ^

**Comment by sewenew** [comment] 2022-05-20 01:32
Not sure if other code in your project conflict with redis-plus-plus. Can you write a simple redis-plus-plus test without other dependency to see if redis-plus-plus works well? For example, try the following code:

```
#include <iostream>
#include <sw/redis++/redis++.h>
using namespace std;
using namespace sw::redis;
int main() {
    try {
        auto r = Redis("tcp://127.0.0.1");
        cout << r.ping() << endl;
    } catch (const Error &e) {
        cout << e.what() << endl;
    }
}
```

Regards

**Comment by sewenew** [comment] 2022-05-27 12:38
Since there's no update, I'll close the issue.

Regards

**Closed by sewenew** 2022-05-27 12:38 UTC
