### ISSUE TITLE
[QUESTION] sw::redis::cluster  how to check connection alive

### ISSUE THREAD

**Issue by blessnhs** [sewenew/redis-plus-plus#529] opened 2023-11-15 02:41 UTC
**Before Asking A Question**
The [README.md file](https://github.com/sewenew/redis-plus-plus/blob/master/README.md) has a detailed introduction with examples on how to use redis-plus-plus, and [redis.h](https://github.com/sewenew/redis-plus-plus/blob/master/src/sw/redis%2B%2B/redis.h) has doxgen style comments for most commands. Before asking a question, please try to find answers with these two files.

For general questions on redis-plus-plus, you can ask questions at StackOverflow with [redis tag](https://stackoverflow.com/questions/tagged/redis), and normally, you'll get faster response on StackOverflow.

However, if you still don't get answers, feel free to ask a question here.

**Describe the problem**
A clear and concise description of the problem, with minimal code to reproduce the problem.

**Environment:**
 - OS: [e.g. ubuntu]
 - Compiler: [e.g. gcc 7.3.1, clang 3.9.1]
 - hiredis version: [e.g. v1.0.0, master]
 - redis-plus-plus version: [e.g. 1.3.2, master, commit b0a42e]

**Additional context**

**Comment by sewenew** [comment] 2023-11-15 23:43
Normally, you don’t need to check the connection. If the connection is broken, the client will automatically reconnect to the cluster when you try to send a new command with the client.

If you do need to do the check, send a ping command to a node returned by RedisCluster::redis(hashtag).


________________________________
发件人: blessnhs ***@***.***>
发送时间: Wednesday, November 15, 2023 10:41:51 AM
收件人: sewenew/redis-plus-plus ***@***.***>
抄送: Subscribed ***@***.***>
主题: [sewenew/redis-plus-plus] [QUESTION] sw::redis::cluster how to check connection (Issue #529)


Before Asking A Question
The README.md file<https://github.com/sewenew/redis-plus-plus/blob/master/README.md> has a detailed introduction with examples on how to use redis-plus-plus, and redis.h<https://github.com/sewenew/redis-plus-plus/blob/master/src/sw/redis%2B%2B/redis.h> has doxgen style comments for most commands. Before asking a question, please try to find answers with these two files.

For general questions on redis-plus-plus, you can ask questions at StackOverflow with redis tag<https://stackoverflow.com/questions/tagged/redis>, and normally, you'll get faster response on StackOverflow.

However, if you still don't get answers, feel free to ask a question here.

Describe the problem
A clear and concise description of the problem, with minimal code to reproduce the problem.

Environment:

  *   OS: [e.g. ubuntu]
  *   Compiler: [e.g. gcc 7.3.1, clang 3.9.1]
  *   hiredis version: [e.g. v1.0.0, master]
  *   redis-plus-plus version: [e.g. 1.3.2, master, commit b0a42e]

Additional context
Add any other context about the problem here.

―

**Comment by sewenew** [comment] 2023-11-18 12:35
Since there's no update, I'll close this issue.

Regards

**Closed by sewenew** 2023-11-18 12:35 UTC
