### ISSUE TITLE
[QUESTION] Performance issue

### ISSUE THREAD

**Issue by manishkrishan** [sewenew/redis-plus-plus#347] opened 2022-03-25 08:56 UTC
I am using **redis-plus-plus** on Windows 10 64 but to connect to redis cluster as below and setting/getting some keys but facing performance issues and exceptions randomly after setting/getting 35-40 keys "**Failed to send command with key**: bootstrap/abcd/user_34"

Performance number surprising, it usually takes more time for first cmd on key either it is **set** or **get** and subsequent cmd respond quickly. 

Please refer attached perf.logs and suggest what could be the issue here. 
[perf.log](https://github.com/sewenew/redis-plus-plus/files/8348932/perf.log)

```
class stopWatch
{
private:
   long int start;
public: 
   stopWatch() {
      start = ::GetTickCount();
   }

   long int getMs() {
      long int end = ::GetTickCount();
      return end - start;
   }
};

std::ofstream redislog;

int _tmain(int argc, _TCHAR* argv[])
{
	//redislog.open(<params>)

	ConnectionOptions connection_options;
	connection_options.host = <host>;
	connection_options.port = <port>;

	ConnectionPoolOptions pool_options;
	pool_options.size = 3;

	gRedisCluster = new sw::redis::RedisCluster(connection_options, pool_options);

	const std::chrono::milliseconds ttl = std::chrono::milliseconds(60000);
	char sKey[100] = {0};
	char sTick[100] = {0};
        char sValue[100] = "sample value for redis cluster";

	try {
		for (int k = 0; k < 50; ++k)  {
                   _snprintf(sKey, 100, "bootstrap/abcd/user_%d", k);
		   stopWatch watch1;
		   redislog << getTime() << " : setValue Key : " << sKey;
		   gRedisCluster->set(sKey, sValue, ttl);
		   _snprintf(sTick, 100, " time (ms) = %ld", watch1.getMs());
		   redislog << sTick << std::endl;

		   stopWatch watch2;
		   redislog << getTime() << " : getValue Key : " << sKey;
		   auto val = gRedisCluster->get(sKey);
		   _snprintf(sTick, 100, " time (ms) = %ld", watch2.getMs());
		   redislog << sTick << std::endl;
		}
     }
   catch(const std::exception & ex) {
      printf("exception = %s . . .\n", ex.what());
   }	
}
```

**Comment by sewenew** [comment] 2022-03-26 06:38
Sorry but I cannot reproduce your problem with Win 10 64bit, Visual Studio 2019. Client works on Windows, and Redis server works on macOS.

You'd better check if the network latency between your client and server. It looks like the network is unstable. Also, you can use the official client tool: redis-cli to do a test.

Regards

**Comment by manishkrishan** [comment] 2022-03-26 06:46
Thankyou for trying it, in my case Redis cluster server is on Linux 7.4 and client is on WIndows 10. 

I also tried with jedis java lib to test the performance but there it is better under same setup but still not perfect as this also taking 200-300 ms to get/set simple key value. Exploring it more.

**Comment by sewenew** [comment] 2022-05-02 15:34
Since there's no update, I'll close this issue.

Regards

**Closed by sewenew** 2022-05-02 15:34 UTC
