### ISSUE TITLE
Disconnected

### ISSUE THREAD

**Issue by 244916896** [sewenew/redis-plus-plus#265] opened 2021-09-03 01:09 UTC
I connect redis in the running program. When I use it in the dynamic library, the connection is gone。I don't know if you have experienced it. Please help. Thank you！

**Comment by 244916896** [comment] 2021-09-03 04:36
I am on the Linux platform. The main program calls the dynamic library through dlopen、dlsym

**Comment by sewenew** [comment] 2021-09-03 14:25
Can you show me a minimum compilable code that can reproduce the problem? Also please tell me which version of redis-plus-plus and hiredis are you using?

Regards

**Comment by 244916896** [comment] 2021-09-06 01:45
You can test it ，write a main program to connect redis global variables to store connection information. Open the dynamic library in dlopen mode, and use the global variable in the dynamic library to call the redis setting or value viewing function. At this time, the global variable is not connected, and you need to connect again to call the setting viewing function.

**Comment by sewenew** [comment] 2021-09-07 15:07
Sorry, but I do not quite understand your scenario. If you can share a minimum compilable code, I can do more help.

Regards

**Comment by sewenew** [comment] 2021-09-10 13:25
Also please check if you installed multiple versions of hiredis. Check [this](https://github.com/sewenew/redis-plus-plus/issues/266) for reference.

Regards

**Comment by sewenew** [comment] 2021-09-20 14:52
Since there’s no update. I’ll close this issue.

**Closed by sewenew** 2021-09-20 14:52 UTC
