### ISSUE TITLE
[BUG] AsyncRedisCluster keep cost fd at idle state

### ISSUE THREAD

**Issue by lisay-yan** [sewenew/redis-plus-plus#559] opened 2024-04-12 03:47 UTC
**Describe the bug**
After new AsyncRedisCluster client, and keep it idle, not send any traffic, I observed the fd keep costing.

**To Reproduce**
Minimal code to reproduce the bug.
client = new AsyncRedisCluster(connection_options, pool_options);
Then, sleep, without any traffic.

**Expected behavior**
Discovery cluster node status, and set up one connection to each node. Keep ESTABLISHED status.

**Environment:**
 - OS: linux
 - Compiler: v 4.8.5
 - hiredis version: v1.0.0
 - redis-plus-plus version: master

**Additional context**
Please provide solution and info for why AsyncRedisCluster keep cost fd after just created, and no traffic drop in.
<img width="824" alt="image" src="https://github.com/sewenew/redis-plus-plus/assets/61861257/0fece2ef-72ec-4752-ba85-5d1d25f213f3">

**Comment by lisay-yan** [comment] 2024-04-12 07:44
Update

Due to Redis cluster passwd required, I didn't set it to cluster client.
After set right passwd, the network behavior is controllable.

But, in the product env, 
if Redis cluster is switch from no passwd to auth required, then existing client is keep costing fd till re-create the redis++ client with passwd.

can I know why so many fd since no traffic?
Any suggestion to prevent fd costing when client No or Wrong passwd???

**Comment by lisay-yan** [comment] 2024-04-12 09:07
One more question.
I found work around if need send a PING, but my response always is "connection is closing".
While, other commands, set/get, looks good. Why?

// Create an AsyncRedis object with hash-tag, so that we can send commands that has no key.// It connects to Redis instance that holds the given key, i.e. hash-tag.
auto r = async_cluster.redis("hash-tag");

Future<string> ping_res = r.command<string>("ping");

**Comment by sewenew** [comment] 2024-04-15 02:03
> can I know why so many fd since no traffic?

Once you create an AsyncRedisCluster object, it tries to connect to a random cluster node, and fetch the slot-node mapping. If it fails, it retries serval times (on other random nodes). Then it sleeps 1 second, and retry fetching the map.

In your case, you set a wrong password, redis-plus-plus always fails to get the slot-node mapping, and closes the connections. That's why you see so many connections.

> Any suggestion to prevent fd costing when client No or Wrong passwd???

Once you send any command to Redis with AsyncRedisCluster, you'll get an exception that password is wrong. And you can handle the error.

> While, other commands, set/get, looks good. Why?

Do you mean, you create an AsyncRedisCluster object with incorrect password, and the ping command throws "connection is closing" exception? I cannot reproduce your problem with the latest code on master. But if I remember correctly, I fixed a similar problem, and you can try if the latest code works well for you.

Regards

**Comment by lisay-yan** [comment] 2024-04-15 02:28
hi,

Yes, I try to use ping to understand the rainy day case, and expected "NOAUTH Authentication required" to take action and prevent fd costing.

But after I set correct password to AsyncRedisCluster, and send ping.
auto r = async_cluster.redis("hash-tag");
Future ping_res = r.command("ping");

Here is my output for set command and ping. It can prove async cluster is normal, while, ping can't work.
[lisay@sessiondbproxy-ci Andy]$ ./11
send set
send set
send set
set val = OK
set val = OK
set val = OK
send ping
e = connection is closing

Is there misusage in my ping?

**Comment by lisay-yan** [comment] 2024-04-15 03:32
If wrong passwd to AsyncRedisCluster, the test result as below

send set
set e = NOAUTH Authentication required.
send ping
e = connection is closing

**Comment by sewenew** [comment] 2024-04-18 01:04
> Is there misusage in my ping?

Have you waited the returned future before destroying the AsyncRedisCluster object? You need to ensure that all commands have been sent and the replies have been received before AsyncRedisCluster is destroyed. Otherwise, when AsyncRedisCluster is destructing, it closes the connection and mark all pending reply as error, i.e. connection is closing.

Regards

**Comment by sewenew** [comment] 2024-06-22 12:16
Since there's no update, I'll close this issue.

Regards

**Closed by sewenew** 2024-06-22 12:16 UTC
