### ISSUE TITLE
Instance declaration without definition

### ISSUE THREAD

**Issue by Sharonlalala** [sewenew/redis-plus-plus#181] opened 2021-03-06 01:22 UTC
Hi @sewenew I wonder know can I declare an RedisCluster or Redis instance without specific definition? The example is in below:
Class MyRedis{
public:
     MyRedis(int port, int size){
        connection_options.host = "127.0.0.1";  // Required.
        connection_options.port = port; 
        MyCluster = RedisCluster(connection_options);
    }
private:
    ConnectionOptions connection_options;
    RedisCluster MyCluster;
}；
When I run it, I got the error that there must be at least one argument. It is the same when I use pointer. Is there a way to do it expect from std::move(newcluster) ? 
Thank you very much!

**Comment by sewenew** [comment] 2021-03-06 03:52
Duplicate of #51

**Closed by sewenew** 2021-03-06 03:52 UTC
