### ISSUE TITLE
[QUESTION] how can i  control the short connection number when i use transaction and watch.

### ISSUE THREAD

**Issue by harkhuang** [sewenew/redis-plus-plus#334] opened 2022-03-08 13:19 UTC
```
        auto tx = _transaction(key, false, false);

        auto redis = tx.redis();

        rediswatch(key);

        // Key has been modified by other client
        _redisset(key, "val");

        // Transaction should fail, and throw WatchError
        txset(key, "1")exec();

        REDIS_ASSERT(false, "failed to test watch");
```
when i use code above i will get a short connection with TIME_WAIT in redis client althought i use redis connection pool

How to avoid generating short connection?

**Comment by sewenew** [comment] 2022-03-08 14:40
Looks like you did not catch the `WatchError` before the `Transaction` object is destroyed. Once an exec failed, e.g. a WatchError happens, `Transaction` will hold the connection, so that user code can retry the connection. However, when `Transaction` is destroyed, it will close the held connection (If `exec` runs successfully, `Transaction` will return the connection to pool, and the destructor of `Transaction` will not close it).

In order to avoid the problem, you should catch possible `WatchError` before `Transaction` is destroyed:

```
auto tx = _transaction(key, false, false);

bool retrying = false;
while (true) {
  try {
      auto redis = tx.redis();
      redis.watch(key);
      if (!retrying)       // when retrying, do not set key to make the transaction successful
          _redis.set(key, "val");
      tx.set(key, "1").exec();
  } catch (const WatchError &e) {
      // transaction fail, retry
      retrying = true;
      continue;
  }
}
```

Check the [doc](https://github.com/sewenew/redis-plus-plus#watch) for example.

Regards

**Comment by harkhuang** [comment] 2022-03-09 01:54
first of all, thank you for your reply.

all my code about like this :

```
    connection_options.host = "127.0.0.1";
    connection_options.port = 7000;
    connection_options.password = "123456;
    pool_options.wait_timeout = std::chrono::milliseconds(100);
    pool_options.connection_lifetime = std::chrono::minutes(10);
    pool_options.size = 50;
    redis_cluster = make_shared<sw::redis::RedisCluster>(connection_options, pool_options);

    for (int i = 0; i <= 10; i++) {
    try {
	  auto transaction = _redis_cluster->transaction( "key", false, false);
      auto redis = transaction.redis();           // short connection code ?
      redis("key",false).watch("key");            // short connection code ?
      auto value = redis.hget("key", "filed");  
      if (value.value() == "") {
        return -1;
      } 
      auto replies = transaction.hset("key", "filed", "val").expire("key", std::chrono::seconds(10)).exec();
      if ((replies.size() != 2 ) { 
        
        return -1;
      }
      break;
    } catch (const sw::redis::WatchError& err) {
      cout << err.what()<< endl;
      continue;
    } catch (const sw::redis::Error& err) {
      cout << err.what()<< endl;
      return  -1;
    } catch (const std::exception& err) {
      cout << err.what()<< endl;
      return -1;
    } catch (...) {
      cout << err.what()<< endl;
      return -1;
    }

1. i use redis cluster in the connection .  (localhost:7000,localhost:7001,localhost:7002)
2. make sure the key  watch and  hset  in same slot.
3. when i call this code 10/seconds  * 10  , than 90 percent  calls  i = 1,there will generate about 50±  short connections.

Regards


why there so much short connections ? how to avoid it?
how can correct use connection pool  in cluster transcation with watch ?


```

> Looks like you did not catch the `WatchError` before the `Transaction` object is destroyed. Once an exec failed, e.g. a WatchError happens, `Transaction` will hold the connection, so that user code can retry the connection. However, when `Transaction` is destroyed, it will close the held connection (If `exec` runs successfully, `Transaction` will return the connection to pool, and the destructor of `Transaction` will not close it).
> 
> In order to avoid the problem, you should catch possible `WatchError` before `Transaction` is destroyed:
> 
> ```
> auto tx = _transaction(key, false, false);
> 
> bool retrying = false;
> while (true) {
>   try {
>       auto redis = tx.redis();
>       redis.watch(key);
>       if (!retrying)       // when retrying, do not set key to make the transaction successful
>           _redis.set(key, "val");
>       tx.set(key, "1").exec();
>   } catch (const WatchError &e) {
>       // transaction fail, retry
>       retrying = true;
>       continue;
>   }
> }
> ```
> 
> Check the [doc](https://github.com/sewenew/redis-plus-plus#watch) for example.
> 
> Regards

**Comment by sewenew** [comment] 2022-03-09 13:57
As I mentioned in the comment above, you should ensure `Transaction` object is not destroyed when catching `WatchError`.

In your case, putting `transaction` outside the for loop should mitigate the problem:

```
auto transaction = _redis_cluster->transaction( "key", false, false);
int i = 0;
for (i = 0; i <= 10; i++) {
    try {
          // your code here
    } catch (const WatchError &e) {
    }
}
if (i == 11) {
    // still fail after retrying 10 times. In this case, if you want to avoid the connection being closed, 
    // make the Transaction object run some command successfully.
    //Otherwise, the connection will be closed.
    transaction.ping().exec();
}
```

Regards

**Comment by harkhuang** [comment] 2022-03-10 14:38
> "putting transaction outside the for loop should mitigate the problem:"

**Comment by harkhuang** [comment] 2022-03-10 16:06
**Thank you very much for your reply.**

I am agree with what you said: "putting transaction outside the for loop should mitigate the problem:"

And I have a new question as follows.

```

void foo()
{
   //When the destructor is called, the connection will 
  // be closed instead of being returned to the connection pool
  auto transaction = _redis_cluster->transaction( "key", false, false);   


  int i = 0;
  for (i = 0; i <= 10; i++) {
      try {
             
      } catch (const WatchError &e) {

      }
  }
  if (i == 11) {
      transaction.ping().exec();
  }

}

//  Call this funciton a lot in a short time . there will be a lots of TIME_WAIT.
//  Did I need to set the transaction handle as a global variable  to avoid the connection being closed.
//  Should i use mutex to ensure  transaction handle  thread safe?

```

**Comment by sewenew** [comment] 2022-03-11 12:42
Looks like the problem is that the `Redis` object created by `Transaction::redis`, has not been released when `exec` is called. In that case, the connection will not be returned to pool when calling exec, and it will be closed when `Transaction` is destroyed.

```
auto transaction = _redis_cluster->transaction( "key", false, false);   
for (I = 0; I <= 10; ++I) {
    try {
          auto r = transaction.redis();
          r.watch(key);
          transaction.set(key, value).exec();     // <---- when exec is called, `r` is still hold the same connection, and the connection will be closed when Transaction is destroyed.
    } catch (const WatchError &e) {
    }
}
```

In order to avoid the problem, you can destroy the newly created Redis object before calling `exec`.

```
try {
    transaction.redis().watch(key);       // <---- the temp Redis object will be destroyed after `watch` is called.
    transaction.set(key, value).exec();   // In this case, the underlying connection will be returned to pool, and it will not be closed when Transaction is destroyed.
} catch (const WatchError &e) {
}
```

Sorry, the code is very tricky! Thanks for finding the problem! I'll try to fix it.

Regards

**Comment by harkhuang** [comment] 2022-03-15 07:01
Thank you. your is code is work. 
but i am not sure the Performance loss caused by frequent calls to  redis object destructors.
try {
    transaction.redis().watch(key);       // <---- the temp Redis object will be destroyed after `watch` is called.
    transaction.set(key, value).exec();   // In this case, the underlying connection will be returned to pool, and it will not be closed when Transaction is destroyed.
} catch (const WatchError &e) {
}

**Comment by sewenew** [comment] 2022-03-15 13:12
Creating a `Redis` object with `Transaction::redis()`, and destroying it, should not be a problem. The underlying implementation only copies a shared_ptr, and destroy it.

You can do some benchmark to test it :)

Regards

**Comment by sewenew** [comment] 2022-03-17 12:17
@harkhuang Since there's no update, I'll close this issue.

Also, if you have any benchmark test result, feel free to post it here :)

Regards

**Closed by sewenew** 2022-03-17 12:17 UTC

**Comment by harkhuang** [comment] 2022-03-18 08:03
yeah  , my pleasure~
