### ISSUE TITLE
redisAsyncContext support  for asynchronous command processing 

### ISSUE THREAD

**Issue by iasna** [sewenew/redis-plus-plus#119] opened 2020-11-14 12:22 UTC

**Comment by sewenew** [comment] 2020-11-15 02:57
Duplicate of #13

**Comment by sewenew** [comment] 2021-05-09 15:10
Async support is out! Although, so far, Redis Cluster, Redis Sentinel, Transaction and Subscriber support are still on the way.

Please check the [doc](https://github.com/sewenew/redis-plus-plus#async-interface) for detail.

Regards

**Comment by sewenew** [comment] 2021-07-26 12:43
Async support has been release with redis-plus-plus 1.3.0.

Regards

**Closed by sewenew** 2021-07-26 12:43 UTC
