### ISSUE TITLE
throws error and can not catch the exception 

### ISSUE THREAD

**Issue by starboy520** [sewenew/redis-plus-plus#258] opened 2021-08-08 13:08 UTC
` int main() {

    ConnectionOptions connection_options;
    connection_options.host="xxxxx";
    connection_options.port=6001          ;
    connection_options.password="xxxxxx"   ;

    RedisCluster cluster1(connection_options);

    string key_prefix = "_test_";
    int i = 0;
    while (true) {
        try {
            {
                string key = key_prefix + std::to_string(i);
                Transaction transaction = cluster1.transaction(key, false, false);
                auto reply = transaction.set(key, key).expire(key, 20).exec();
                auto aa = cluster1.get(key);
                if (*aa != key) {
                    cout << "input: " << key << " output: " << *aa << endl;
                }
            }
        } catch(const sw::redis::IoError& err) {
            cout << err.what() << endl;
        } catch(const sw::redis::Error &err) {
            cout << err.what() << endl;
        } catch(...) {
            cout << "what the fucking" << endl;
        }

        i++;
}
`

i am simulating one node fail.
when i  kill one master node , the code core dump :  in 
            Transaction transaction = cluster1.transaction(key, false, false);
why?
the catch block seems cannot catches...

terminate called after throwing an instance of 'sw::redis::IoError'
  what():  Failed to connect to Redis: Connection refused
[1]    61818 abort (core dumped)  ./a.out

**Comment by sewenew** [comment] 2021-08-08 15:12
What’s the version of redis++ do you use? The behavior looks like a bug fixed before. See [this commit](https://github.com/sewenew/redis-plus-plus/commit/a6225e0b29b561dc763c17589c4d0c77479a2634#diff-d9d84663cfb54257339df355ace1c1b379857874ad9c6082acf56d5f27bbeb11) and [this issue](https://github.com/sewenew/redis-plus-plus/issues/172) for detail.

If you didn’t use the latest code of redis++, please try the latest code for a test.

Regards

**Comment by starboy520** [comment] 2021-08-09 02:37
@sewenew  thanks, I upgrade the version 1.3.0,  that's fix .

but， when the master becomse reachable, the program still thows exception     } catch(const sw::redis::Error &err) {
        cout << err.what() << endl;


It prints.  host:ip

why ? 

should I new a connection or a client transaction ?

**Comment by sewenew** [comment] 2021-08-09 14:57
First of all, you are always recommended to update to the latest release (so far, it's 1.3.1), or the master branch.

> It prints. ${integer} ${host}:${ip} why ?

Because it received a MOVED or ASK error, since the old master has been changed to slave. You can catch it by `const MovedError &e` or `const AskError &e`. `Transaction` cannot handle these errors.

> should I new a connection or a client transaction ?

As I mentioned in the doc, once `Transaction` throws an exception other than `ReplyError`, you need to destroy the `Transaction` object, and create a new one.

Regards

**Comment by starboy520** [comment] 2021-08-10 07:15
> First of all, you are always recommended to update to the latest release (so far, it's 1.3.1), or the master branch.
> 
> > It prints. ${integer} ${host}:${ip} why ?
> 
> Because it received a MOVED or ASK error, since the old master has been changed to slave. You can catch it by `const MovedError &e` or `const AskError &e`. `Transaction` cannot handle these errors.
> 
> > should I new a connection or a client transaction ?
> 
> As I mentioned in the doc, once `Transaction` throws an exception other than `ReplyError`, you need to destroy the `Transaction` object, and create a new one.
> 
> Regards

I know I should discard the Transaction, But  with my code,   I get the Transaction from The RedisCluster, There seems no api to explicitly  discard the Transaction from the RedisCluster ?

**Comment by starboy520** [comment] 2021-08-10 08:32
```
If master is down, the cluster will promote one of its replicas to be the new master. redis-plus-plus can also handle this case:

When the master is down, redis-plus-plus losts connection to it. In this case, if you try to send commands to this master, redis-plus-plus will try to update slot-node mapping from other nodes. If the mapping remains unchanged, i.e. new master hasn't been elected yet, it fails to send command to Redis Cluster and throws exception.
When the new master has been elected, the slot-node mapping will be updated by the cluster. In this case, if you send commands to the cluster, redis-plus-plus can get an update-to-date mapping, and sends commands to the new master.

```


But the transaction from RedisCluster.transaction. seems not handle this case ?

**Comment by starboy520** [comment] 2021-08-10 11:46
I found the https://github.com/sewenew/redis-plus-plus/issues/60,  how I do this in RedisCluster

**Comment by sewenew** [comment] 2021-08-10 13:39
> But with my code, I get the Transaction from The RedisCluster, There seems no api to explicitly discard the Transaction from the RedisCluster ?

Yes, this is correct way to destroy the old Transaction, and create a new one, i.e. call `RedisCluster::transaction` again.

> But the transaction from `RedisCluster::transaction`. seems not handle this case ?
> does transaction received MovedError but not update the slot ?

Yes, the Transaction code doesn't handle Moved error, and the slot mapping does not been updated. So you got the `MovedError` exception.

Your scenario, i.e. only transaction is called on the key that is being moved, was not considered, and that's bug. Sorry for the inconvenience. I checked the code, and it's not easy to fix. Since the transaction has no reference to the underlying `ShardsPool`.

The best solution to this problem is to use Lua script, i.e. `RedisCluster::eval`, instead of transaction. However, if you insist on using transaction, a workaround to the problem is that once you catch a `MovedError` when working with `Transaction`, you create a new `RedisCluster` object. If this is too expensive for you (since you need to reconnect those nodes), instead of creating a new `RedisCluster`, you can call `RedisCluster::get(the-key-related-to-the-transaction)` to make redis-plus-plus update the underlying slot mapping.

I'll take a deep look into this problem to see if there's a better solution for it.

Regards

**Comment by starboy520** [comment] 2021-08-11 03:22
@sewenew  thanks ，  actually I need hset and expire,   i will try lua script, thanks

**Comment by starboy520** [comment] 2021-08-11 08:13
@sewenew   When I add a new node or remove a node from the cluster ,  it thows some error with :

Failed to send command with key: xxxx

**Comment by sewenew** [comment] 2021-08-11 14:48
Did you set `cluster-require-full-coverage no`? If you do, you might got the problem, and you can try the slot-coverage branch.

If you didn't do that, this exception is thrown when redis-plus-plus cannot update the slot mapping. Possible failure are commented in the code. Normally, you only need to retry the command after a while. Once the cluster is stable, everything will be fine.

Regards

**Comment by starboy520** [comment] 2021-08-15 08:44
> Did you set `cluster-require-full-coverage no`? If you do, you might got the problem, and you can try the slot-coverage branch.
> 
> If you didn't do that, this exception is thrown when redis-plus-plus cannot update the slot mapping. Possible failure are commented in the code. Normally, you only need to retry the command after a while. Once the cluster is stable, everything will be fine.
> 
> Regards

**Comment by sewenew** [comment] 2021-08-16 14:27
Sorry, but I cannot reproduce your problem. Normally, as I mentioned in above comment, if you retry the operation in a loop, and when the cluster recovers, you won't get the moved error.

Can you show me your code that can compile and reproduce the problem? Also please show me your Redis Cluster topology, the steps you did to make a master node down, and how you recover the cluster?

Regards

**Comment by starboy520** [comment] 2021-08-17 02:11
I just add new nodes or remove nodes from the cluster.  not make the master down.

`
int main() {
    ConnectionOptions connection_options;
    connection_options.host="xxx";
    connection_options.port=6001          ;
    connection_options.password="xxxx"   ;
    connection_options.keep_alive=true;
    connection_options.connect_timeout = std::chrono::milliseconds{5000};
    connection_options.socket_timeout = std::chrono::milliseconds{5000};
    ConnectionPoolOptions option;
    option.size = 1;
    RedisCluster cluster1(connection_options, option);
    string key_prefix = "xxxx_test_";
    int i = 0;
    string lua_script = "redis.call('set', KEYS[1], ARGV[1]);redis.call('expire', KEYS[1], ARGV[2]);return 1;";
    int failure = 0;
    while (true) {
        std::string key = key_prefix + std::to_string(i);
        try {
                cluster1.setex(key, 20, key);
                auto result = cluster1.eval<long long>(lua_script, {key}, {key, "20"});
                auto aa = cluster1.get(key);
                //cout << *aa << endl;
                if (*aa != key) {
                    cout << "input: " << key << " output: " << *aa << endl;
                }
        } catch(const sw::redis::IoError& err) {
            cout << "io error " << err.what() << endl;
        } catch(const sw::redis::MovedError& err) {
            cout << "move  discard: " << err.what() << endl;
        } catch(const sw::redis::AskError& err) {
            cout << "ask discard2: " << err.what() << endl;
        } catch(const sw::redis::Error &err) {
            cout << "base: " << err.what() << endl;
        } catch(...) {
            cout << "what"  << endl;
        }
        i++;
    }
    return 0;
}
`

**Comment by sewenew** [comment] 2021-08-17 13:52
When all keys of a given slot have been moved, you need to call `CLUSTER SETSLOT slot-number NODE node-id` on both the source node, and the destination node. If you send command to after the source node running `CLUSTER SETSLOT slot-number NODE node-id`, and before the destination node running `CLUSTER SETSLOT slot-number NODE node-id`, the client will be redirected by both source node, and destination node. In that case, you'll got *Failed to send command with key:*.

If this is your case, no worry about it. When you call `CLUSTER SETSLOT slot-number NODE node-id` on both nodes, everything will be fine.

Regards

**Comment by starboy520** [comment] 2021-08-17 23:47
> When all keys of a given slot have been moved, you need to call `CLUSTER SETSLOT slot-number NODE node-id` on both the source node, and the destination node. If you send command to after the source node running `CLUSTER SETSLOT slot-number NODE node-id`, and before the destination node running `CLUSTER SETSLOT slot-number NODE node-id`, the client will be redirected by both source node, and destination node. In that case, you'll got _Failed to send command with key:_.
> 
> If this is your case, no worry about it. When you call `CLUSTER SETSLOT slot-number NODE node-id` on both nodes, everything will be fine.
> 
> Regards

https://redis.io/topics/cluster-spec#cluster-live-reconfiguration  @sewenew  we used the migrating command:

"
```
The SETSLOT subcommand is used to assign a slot to a specific node ID if the SETSLOT <slot> NODE form is used. Otherwise the slot can be set in the two special states MIGRATING and IMPORTING. Those two special states are used in order to migrate a hash slot from one node to another.

When a slot is set as MIGRATING, the node will accept all queries that are about this hash slot, but only if the key in question exists, otherwise the query is forwarded using a -ASK redirection to the node that is target of the migration.
When a slot is set as IMPORTING, the node will accept all queries that are about this hash slot, but only if the request is preceded by an ASKING command. If the ASKING command was not given by the client, the query is redirected to the real hash slot owner via a -MOVED redirection error, as would happen normally.
Let's make this clearer with an example of hash slot migration. Assume that we have two Redis master nodes, called A and B. We want to move hash slot 8 from A to B, so we issue commands like this:

We send B: CLUSTER SETSLOT 8 IMPORTING A
We send A: CLUSTER SETSLOT 8 MIGRATING B
All the other nodes will continue to point clients to node "A" every time they are queried with a key that belongs to hash slot 8, so what happens is that:

All queries about existing keys are processed by "A".
All queries about non-existing keys in A are processed by "B", because "A" will redirect clients to "B".
This way we no longer create new keys in "A". In the meantime, redis-cli used during reshardings and Redis Cluster configuration will migrate existing keys in hash slot 8 from A to B. This is performed using the following command:

```


"

**Comment by sewenew** [comment] 2021-08-18 13:36
> it seems we should handl this case gracefuly?

Yes, this will be handled gracefully.

You can write a loop to do the test:

```
while (true) {
   try {
       auto val = cluster.get("key");
       if (val) cout << *val << endl;
       else cout << "not exist" << endl;
   } catch (const Error &e) {
       cout << "err: " << e.what() << endl;
   }
   this_thread::sleep_for(chrono::seconds(1));
}
```

When you move the slot related to "key" from one node to another, you'll see the code output something like the following (say, the value at "key" is "val"):

```
// before moving slot
val
val
...
val
// during moving, you might get error message
err: xxxx
err: xxxx
...
err: xxx
// finish moving, and all set
val
val
val
...
```

Regards

**Comment by sewenew** [comment] 2021-08-28 08:52
Since there's no update on this issue. I'll close it. If you still have problems, feel free to reopen it.

Regards

**Closed by sewenew** 2021-08-28 08:52 UTC
