### ISSUE TITLE
Using it on Windows

### ISSUE THREAD

**Issue by manishkrishan** [sewenew/redis-plus-plus#333] opened 2022-03-07 12:49 UTC
**Describe the problem**
I compiled on redis-plus-plus along with hiredis on Windows 64 with VS2019 using ISO C++17 as static lib. I am trying to use it in a new project (newly created without any other source code)

I have simply included "redis++.h" header with dummy method and on compiling it, lots of compile errors as below:

```
1>RedisWrapper.cpp
1>D:\_Redis\header\hiredis\sds.h(53): warning C4200: nonstandard extension used: zero-sized array in struct/union
1>D:\_Redis\header\hiredis\sds.h(53): note: This member will be ignored by a defaulted constructor or copy/move assignment operator
1>D:\_Redis\header\hiredis\sds.h(59): warning C4200: nonstandard extension used: zero-sized array in struct/union
1>D:\_Redis\header\hiredis\sds.h(59): note: This member will be ignored by a defaulted constructor or copy/move assignment operator
1>D:\_Redis\header\hiredis\sds.h(65): warning C4200: nonstandard extension used: zero-sized array in struct/union
1>D:\_Redis\header\hiredis\sds.h(65): note: This member will be ignored by a defaulted constructor or copy/move assignment operator
1>D:\_Redis\header\hiredis\sds.h(71): warning C4200: nonstandard extension used: zero-sized array in struct/union
1>D:\_Redis\header\hiredis\sds.h(71): note: This member will be ignored by a defaulted constructor or copy/move assignment operator
1>D:\_Redis\header\hiredis\sds.h(77): warning C4200: nonstandard extension used: zero-sized array in struct/union
1>D:\_Redis\header\hiredis\sds.h(77): note: This member will be ignored by a defaulted constructor or copy/move assignment operator
1>D:\_Redis\header\redis++\command_options.h(64): warning C4003: not enough arguments for function-like macro invocation 'min'
1>D:\_Redis\header\redis++\command_options.h(66): warning C4003: not enough arguments for function-like macro invocation 'max'
1>D:\_Redis\header\redis++\command_options.h(64): error C2059: syntax error: ')'
1>D:\_Redis\header\redis++\command_options.h(64): error C2334: unexpected token(s) preceding ':'; skipping apparent function body
1>D:\_Redis\header\redis++\command_options.h(67): error C2143: syntax error: missing ')' before ';'
1>D:\_Redis\header\redis++\command_options.h(67): error C2059: syntax error: ')'
1>D:\_Redis\header\redis++\command_options.h(67): error C2238: unexpected token(s) preceding ';'
1>D:\_Redis\header\redis++\command_options.h(74): warning C4003: not enough arguments for function-like macro invocation 'min'
1>D:\_Redis\header\redis++\command_options.h(78): warning C4003: not enough arguments for function-like macro invocation 'max'
```

Included additional include directories for all headers in `hiredis` and `redis++` headers. Am I missing some preprocessor here or something else ?

**Environment:**
 - OS: [Windows 10 x64]
 - Compiler: [VS2019 using ISO C++17]
 - hiredis version: [master]
 - redis-plus-plus version: [master]

**Comment by sewenew** [comment] 2022-03-07 14:24
This should already been fixed. The problem is that Windows has a `min` and `max` macro. I've fixed the problem by specifying `NOMINMAX` in CMakeLists.txt. Check [this](https://github.com/sewenew/redis-plus-plus/issues/38) for detail.

Not sure if you include some other header files or set some compiler options that disables `NOMINMAX` option.

Regards

**Comment by manishkrishan** [comment] 2022-03-08 04:38
Thanks for input, as I mentioned in above query, this is a new project where I am using `hiredis` and `redis++` as static lib. This project is not based on cmake (I am not good in cmake). Hence I created an independent `vcxproj` file to create a new DLL and referred `hiredis` and `redis++` as static lib.

Anyway, defining `NOMINMAX` as preprocessor in vcxproj  fixed the above compile errors. Thankyou again for quick input.

**Comment by sewenew** [comment] 2022-05-02 15:36
Since there's no update, I'll close this issue.

Regards

**Closed by sewenew** 2022-05-02 15:36 UTC
