### ISSUE TITLE
I had a memory leak when I was using the Publish feature

### ISSUE THREAD

**Issue by white-black-hong** [sewenew/redis-plus-plus#196] opened 2021-03-29 04:30 UTC
Here is my code:
Setting Global Variables
       Redis       *m_redis;
In a thread, Initialize the connection
        ConnectionOptions connection_options;
        connection_options.host = redis_host;
        connection_options.port = redis_port;
        connection_options.password = redis_password;

        ConnectionPoolOptions pool_Options;
        pool_Options.size = 10;
        m_redis  = new Redis(connection_options, pool_Options);
Called in another thread
        m_policy->publish("TopicPositionInfo", str);

I have a memory leak during the pressure test. What is the reason? 
@sewenew

**Comment by sewenew** [comment] 2021-03-29 14:27
Can you give me a minimum complete code that can reproduce your problem?

Regards

**Comment by white-black-hong** [comment] 2021-03-30 07:42
This is a multithreaded project, with one thread per account

I initialize the connection in the main function and set a global variable :m_redis

Redis *m_redis;

int main() {

std::string value;

Config configSettings(ConfigFile);

std::string redis_host = configSettings.Read("redis_host", value).c_str();

int redis_port = configSettings.Read("redis_port", 0);

std::string redis_password = configSettings.Read("redis_password", value).c_str();

try {

ConnectionOptions connection_options;

connection_options.host = redis_host;

connection_options.port = redis_port;

connection_options.password = redis_password;

m_redis = new Redis(connection_options);

} catch (const sw::redis::IoError &ex) {

spdlog::error(ex.what());

}

..........
// Open multiple threads

return 0;

}

Use m_redis in the asynchronous callback function in trade.cpp

extern Redis *m_redis;

OnRTNPositionProfit is one of the asynchronous callback functions

void TAP_CDECL Trade::OnRtnPositionProfit( const TapAPIPositionProfitNotice *info )

{

if (info->IsLast == 'Y') return;



spdlog::info("{} is called.", __FUNCTION__);



if (info ! = NULL) {

Json::Value jObject;

std::string IsLast(1, info->IsLast);

jObject["IsLast"] = IsLast;

jObject["PositionNo"] = info->Data->PositionNo;

jObject["PositionStreamId"] = info->Data->PositionStreamId;

jObject["PositionProfit"] = info->Data->PositionProfit;

jObject["LMEPositionProfit"] = info->Data->LMEPositionProfit;

jObject["OptionMarketValue"] = info->Data->OptionMarketValue;

jObject["CalculatePrice"] = info->Data->CalculatePrice;



std::string str = jObject.toStyledString();
spdlog::info("OnRtnPositionProfit: {}", str);

try {

m_redis->publish("TopicPositionInfo", str);

} catch (const sw::redis::Error &err) {

// other errors

spdlog::error("RedisError: {}", err.what());

}

}

}

I may not be making myself clear. Please ask if you don't understand
@sewenew

**Comment by sewenew** [comment] 2021-03-31 00:43
Since your code is not complete, I cannot compile it to reproduce the problem. However, I tried the following test code, and run it for a long time. There's no memory leak problems. You can try the test code, or modify it to reproduce your problem, if you still get the memory leak problem, feel free to let me know.

```
Redis *m_redis;

int main() {
    try {
        ConnectionOptions opts;
        opts.host = "127.0.0.1";
        opts.port = 6379;
        ConnectionPoolOptions pool_Options;
        pool_Options.size = 10;
        m_redis = new Redis(opts, pool_Options);
        vector<thread> workers;
        int N = 10;
        for (auto idx = 0; idx < N; ++idx) {
            workers.emplace_back([]() {
                    try {
                        while (true) {
                            m_redis->publish("topic", "this is a long message");
                        }
                    } catch (const Error &e) {
                        cout << e.what() << endl;
                    }
            });
        }

        for (auto &worker : workers) {
            worker.join();
        }

    } catch (const Error &e) {
        cout << e.what() << endl;
    }
    return 0;
}
```

Regards

**Comment by sewenew** [comment] 2021-04-24 03:08
@white-black-hong Since I didn't get any new reply from you, I'll close this issue. If you still have any problem on it, feel free to reopen it.

Regards

**Closed by sewenew** 2021-04-24 03:08 UTC
