### ISSUE TITLE
core dumped: Assertion `!connection.broken()' failed !

### ISSUE THREAD

**Issue by Hugosuperman** [sewenew/redis-plus-plus#61] opened 2020-06-02 07:00 UTC
An error occurred when I run the test code:
try {
    // Create an Redis object, which is movable but NOT copyable.
    auto redis = Redis("tcp://127.0.0.1:6379");

    // ***** STRING commands *****

    redis.set("key", "val");
    auto val = redis.get("key");    // val is of type OptionalString. See 'API Reference' section for details.
    if (val) {
        // Dereference val to get the returned value of std::string type.
        std::cout << *val << std::endl;
    }   // else key doesn't exist.

    // ***** LIST commands *****

    // std::vector<std::string> to Redis LIST.
    std::vector<std::string> vec = {"a", "b", "c"};
    redis.rpush("list", vec.begin(), vec.end());

    // std::initializer_list to Redis LIST.
    redis.rpush("list", {"a", "b", "c"});

    // Redis LIST to std::vector<std::string>.
    vec.clear();
    redis.lrange("list", 0, -1, std::back_inserter(vec));
    } catch (const Error &e) {
    cout << e.what() << endl；
    }
Assertion `!connection.broken()' failed.
But redis set and get be successful.And this error will also occur when calling template command function like "lrange" "hmset" and so on.I hope get your help. thanks!

**Comment by sewenew** [comment] 2020-06-02 07:59
Hi @Hugosuperman 

I cannot reproduce the problem with the latest code on master branch compiling with GCC7.

Can you show me the version/branch of redis-plus-plus and hiredis you are using? And with which compiler (GCC + version or Clang + version) on which platform (Linux or MacOS)? Also please show me the complete code.

Thanks & Regards

**Comment by Hugosuperman** [comment] 2020-06-02 08:29
Hi @sewenew
thanks for the quick reply.
the version of GCC is 4.8.5,and redis-plus-plus and hiredis is latest master branch.Maybe I should try to use the later versions of GCC 7? ha-ha, when I have tried, I will reply again!
the complete code:
//.h
class ClusterTest
{
public:
    ClusterTest(const ConnectionOptions &connection_opts, const ConnectionPoolOptions& pool_options);
    bool LRange(const string& list_name, list<string>& value); 
    bool HMset(const string& table_name, const map<string, string>& field_pairs);
private:
    RedisCluster redis_cluster_;
};
//.cpp
ClusterTest::ClusterTest(const ConnectionOptions &connection_opts, const ConnectionPoolOptions& pool_options) : redis_cluster_(RedisCluster(connection_opts, pool_options))
{

}
bool ClusterTest::LRange(const string& list_name, list<string>& value)
{
    // list<OptionalString> val;
    // auto r = redis_cluster_.command("lrange", 0, -1, list_name);
    // reply::to_array(*r, back_inserter(val));
    redis_cluster_.lrange(list_name, 0, 1, back_inserter(value));
    return !value.empty();
}
bool ClusterTest::HMset(const string& table_name, const map<string, string>& field_pairs)
{
    try
    {
        redis_cluster_.hmset(table_name, field_pairs.begin(), field_pairs.end());
        //redis_cluster_.command<void>("hmset", );
    }
    catch (const ReplyError &err) {
    // WRONGTYPE Operation against a key holding the wrong kind of value
        cout << "ReplyError\n";
        cout << err.what() << endl;
    } catch (const TimeoutError &err) {
        cout << "TimeoutError\n";
        // reading or writing timeout
    } catch (const ClosedError &err) {
        cout << "ClosedError\n";
        // the connection has been closed.
    } catch (const IoError &err) {
        cout << "IoError\n";
        // there's an IO error on the connection.
    } catch (const Error &err) {
    // other errors
        cout << "Error\n";
    }
}
//main.cpp
int main()
{
    ConnectionOptions connection_options;
    connection_options.host = "192.168.245.131";
    connection_options.port = 7000;

    ConnectionPoolOptions pool_options;
    pool_options.size = 3;
    shared_ptr<ClusterTest> cluster_ptr = make_shared<ClusterTest>(connection_options, pool_options);
    string list_name("list_test");
    list<string> val_list;
    cluster_ptr->LRange(list_name, val_list);
    // map<string, string> t_map;
    // t_map.insert(make_pair("field1", "value1"));
    // t_map.insert(make_pair("field2", "value2"));
    // t_map.insert(make_pair("field3", "value3"));
    // cluster_ptr->HMset("table1", t_map);
}
Thanks & Regards

**Comment by Hugosuperman** [comment] 2020-06-02 09:41
Hi @sewenew sewenew
Can you tell me the version of redis you used? 
thanks!

**Comment by sewenew** [comment] 2020-06-02 11:08
Hi @Hugosuperman 

I tried your code with GCC 4.8.5, but still cannot reproduce the problem...

Can you use GDB to show me the stack trace of the core dump? So that I can have a deeper look at the problem. Thanks!

B.T.W. I'm using Redis-5.0.5.

Regards

**Comment by sewenew** [comment] 2020-10-12 13:00
@Hugosuperman Since I cannot reproduce the problem, I'll close it. If you can give more info, feel free to reopen it.

Regards

**Closed by sewenew** 2020-10-12 13:00 UTC

**Comment by brucejee** [comment] 2022-06-13 06:46
I also meet this coredump，I create a Redis object in a thread, and use it's hget method in another thread, my coredump stack like this, i use gcc 4.8.5 and Redis-6.2.5 ：
```cpp
Program terminated with signal 6, Aborted.
#0  0x00007f5396e62277 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56        return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
Missing separate debuginfos, use: debuginfo-install keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-8.el7.x86_64 libcom_err-1.42.9-10.el7.x86_64 libselinux-2.5-11.el7.x86_64 pcre-8.32-17.el7.x86_64
(gdb) bt
#0  0x00007f5396e62277 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f5396e63968 in __GI_abort () at abort.c:90
#2  0x00007f5396e5b096 in __assert_fail_base (fmt=0x7f5396fb6580 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=assertion@entry=0xf243f5 "!_connection.broken()",
    file=file@entry=0xf255f8 "/home/hft/hft_3rd/hft_ami/../include/sw/redis++/connection_pool.h", line=line@entry=123,
    function=function@entry=0xf3a260 <_ZZN2sw5redis14SafeConnectionC1ERNS0_14ConnectionPoolEE19__PRETTY_FUNCTION__> "sw::redis::SafeConnection::SafeConnection(sw::redis::ConnectionPool&)") at assert.c:92
#3  0x00007f5396e5b142 in __GI___assert_fail (assertion=0xf243f5 "!_connection.broken()",
    file=0xf255f8 "/home/hft/hft_3rd/hft_ami/../include/sw/redis++/connection_pool.h", line=123,
    function=0xf3a260 <_ZZN2sw5redis14SafeConnectionC1ERNS0_14ConnectionPoolEE19__PRETTY_FUNCTION__> "sw::redis::SafeConnection::SafeConnection(sw::redis::ConnectionPool&)") at assert.c:101
#4  0x00000000009326d5 in sw::redis::SafeConnection::SafeConnection(sw::redis::ConnectionPool&) ()
#5  0x0000000000ecac31 in std::enable_if<!std::is_convertible<void (*)(sw::redis::Connection&, sw::redis::StringView const&, sw::redis::StringView const&), sw::redis::StringView>::value, std::unique_ptr<redisReply, sw::redis::ReplyDeleter> >::type sw::redis::Redis::command<void (*)(sw::redis::Connection&, sw::redis::StringView const&, sw::redis::StringView const&), sw::redis::StringView const&, sw::redis::StringView const&>(void (*)(sw::redis::Connection&, sw::redis::StringView const&, sw::redis::StringView const&), sw::redis::StringView const&, sw::redis::StringView const&) ()
#6  0x0000000000ec55ad in sw::redis::Redis::hget(sw::redis::StringView const&, sw::redis::StringView const&) ()
#7  0x00000000008e6f23 in FailbackinfoManager::GetFailbackinfo(std::string const&, CFailbackinfo&) ()
#8  0x000000000093ddb0 in FailbackinfoManager::GetFailbackInfo(int, int, CFailbackinfo&) ()
#9  0x0000000000959b82 in QueryFailbackWorker::ParseFailbackAndPush(std::string const&, unsigned long&) ()
#10 0x000000000095a389 in QueryFailbackWorker::QueryFailback(bool) ()
#11 0x000000000095a8bd in QueryFailbackWorker::dojob() ()
#12 0x0000000000933e59 in ec::cThread::ThreadProcess(void*) ()
#13 0x00007f53977c6360 in std::(anonymous namespace)::execute_native_thread_routine (__p=<optimized out>)
    at ../../../../../libstdc++-v3/src/c++11/thread.cc:84
#14 0x00007f539ad29e25 in start_thread (arg=0x7f5333fff700) at pthread_create.c:308
#15 0x00007f5396f2abad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

**Comment by brucejee** [comment] 2022-06-13 13:56
> @brucejee Can you give me a minimum compilable code that can reproduce the problem? Also, can you try the latest code of redis-plus-plus to see if it's still a problem?
> 
> Regards

@sewenew  I fix the problem, this cause by redis-plus-plus library compile by c++7.2.0, and the application compile by g++4.8.5, my compile env have two compilers, when compile redis++, cmake select /usr/local/bin/c++ as compiler，when compile app, cmake select /usr/bin/c++ as compiler, I delete /usr/local/bin/c++ and /usr/local/bin/g++, the abort coredump is fixed.

**Comment by sewenew** [comment] 2022-06-13 14:31
@brucejee Congratulations!

Regards

**Comment by brucejee** [comment] 2022-06-13 15:20
> @brucejee Congratulations!
> 
> Regards

Thank you very much！
