### ISSUE TITLE
Failed to initialize TLS connection: SSL_connect failed: certificate verify failed

### ISSUE THREAD

**Issue by mgornicki** [sewenew/redis-plus-plus#102] opened 2020-10-01 19:30 UTC
Following code: 
```cpp
ConnectionOptions opts;
opts.type = ConnectionType::TCP;
opts.db = 1;
opts.host = "ip";
opts.port = port;
opts.password = "pass";
opts.tls.enabled = true;
auto redis = Redis(opts);
```
throws: **Failed to initialize TLS connection: SSL_connect failed: certificate verify failed**

**Comment by sewenew** [comment] 2020-10-02 02:08
@mgornicki If you want to use TLS/SSL with redis-plus-plus, you should also specify other tls options, e.g. path to certificate file, path to key file. Check [this](https://github.com/sewenew/redis-plus-plus#connection-options) for detail.

NOTE: although these options are optional, if your Redis server requires these files, you have to specify them with the tls option. Check [this](https://github.com/redis/redis/blob/unstable/TLS.md) for how to setup Redis server with TLS support, and how to connect to it with redis-cli. redis-plus-plus' tls options are the same as redis-cli.

Regards

**Comment by mgornicki** [comment] 2020-10-02 15:38
Thank you for quick response.
My Redis server doesn't require those files.
It's configured to use SSL but without additional files.
I'm using RedisDesktopManager for Windows to connect to that Redis server so I can confirm that it's working without those files.

Reards

**Comment by sewenew** [comment] 2020-10-03 02:31
@mgornicki Do you use Redis 6's built-in support to setup a Redis server with SSL? or you setup SSL with other method?

I tried to setup a Redis 6 server without specifying certificate files, but failed. It seems that we have to specify these files.

Also, can you connect to your redis server (enabled with SSL) with the official redis-cli? If redis-cli doesn't work, redis-plus-plus cannot connect to it either. In that case, you can open an issue for [hiredis](https://github.com/redis/hiredis), since redis-plus-plus is a wrapper of hiredis, and it delegates the connection work to hiredis.

Regards

**Comment by sewenew** [comment] 2020-10-12 13:05
@mgornicki Since I cannot reproduce the problem, I'll close it. If you can connect your server with redis-cli, while cannot connect it with redis-plus-plus, feel free to reopen it.

Regards

**Closed by sewenew** 2020-10-12 13:05 UTC
