### ISSUE TITLE
Async hgetall() - Is the result struct wrong?

### ISSUE THREAD

**Issue by mlanzuisi** [sewenew/redis-plus-plus#503] opened 2023-07-21 13:27 UTC
Hi,

I tried implementing the synchronous and asynchronous "hgetall()" function, but I have issues with the asynchronous part.
When trying to run the following code (as desribed in Readme):

std::future<std::vector<std::string>>    future = m_async_redis_cluster->hgetall<std::vector<std::string>>(key_sw);
for (const auto &ele : future.get())
    std::printf("HGetAll async string \"%s\"\n", ele.c_str());

or simply using

future.get()

I got the following error:

"expect ARRAY or SET reply, but got UNKNOWN reply"

Am I doing anything wrong here?

**Comment by sewenew** [comment] 2023-07-23 04:23
Sorry, but I cannot reproduce your problem with the latest redis-plus-plus code.

Please give version info of redis-plus-plus, hiredis, and Redis-server. Also give a smallest compilable code that can reproduce the problem.

Regards

**Comment by sewenew** [comment] 2023-07-23 04:26
By the way, the example given in README is not a good one, I'll fix it ASAP. Since hgetall returns key-value pairs, you'd better use an unordered_map as the template parameter.

```
auto res = m_async_redis_cluster->hgetall<std::unordered_map<std::string, std::string>>("hash");
```

**Comment by mlanzuisi** [comment] 2023-07-24 07:02
Using your last comment solved my issue, now it works with the unordered map future

**Comment by sewenew** [comment] 2023-07-25 13:53
I know what the problem is. Looks like you used RESP3, in this case, HGETALL returns a map reply instead of an array reply. So when you try to parse it as a vector, it throws the exception. Instead, you need to parse it as a map or unordered_map.

Thanks for finding the corner case! I'll close this issue. If you still have problem, feel free to reopen it :)

Regards

**Closed by sewenew** 2023-07-25 13:53 UTC

**Comment by mlanzuisi** [comment] 2023-07-25 13:55
Yes, you are right. I use RESP3.

Thank you and regards
