### ISSUE TITLE
how to create a redis++ connect object  as a class member?

### ISSUE THREAD

**Issue by yitian108** [sewenew/redis-plus-plus#152] opened 2021-01-19 09:39 UTC
I try to create a redis++ object as a privated class member, and initialize it in constructor function, but error report that we can't do that.

`// A.h
class A
{
public:
A();
~A();

privated:
Redis redis;
}

// A.cpp
#include "A.h"

A::A()
{
        ConnectionOptions connection_options;
        connection_options.host = "*****";  // Required.
        connection_options.password = "*******";   // Optional. No password by default.
        redis = std::move(Redis(connection_options));
}`

error will occur: _error: no matching function for call to ‘sw::redis::Redis::Redis()’_ A::A() {}

Is there any good method to declare a Redis object as a class member?

Regards

**Comment by sewenew** [comment] 2021-01-19 14:28
Duplicate of #51

**Comment by sewenew** [comment] 2021-01-19 14:29
The duplicated issue gives 3 solutions. Please check it for detail.

Regards

**Closed by sewenew** 2021-01-19 14:28 UTC
