### ISSUE TITLE
Bug with tcmalloc : Attempt to free invalid pointer - Aborted (core dumped)

### ISSUE THREAD

**Issue by mohitmv** [sewenew/redis-plus-plus#101] opened 2020-09-25 17:54 UTC
Here is the simplest bug repro.

```
#include <string>
#include <iostream>
#include <unordered_map>

#include "redis++/redis++.h"

#include "common/exported_metric2.hpp"

// This function is never called but the tcmalloc fails only if this function exists.
void F(sw::redis::Redis* r, const std::string& key, const std::string& field) {
  r->hget(key, field);
}

int main(int argc, char** argv) {
  std::cout << "LINE: " << __LINE__ << std::endl;
  common::ExportedMetricContainer2 c;
  (void) c;  // tcmalloc crashing here.
  std::cout << "LINE: " << __LINE__ << std::endl;
  return 0;
}
```

Whereis our class `ExportedMetricContainer2` is as simple as:

```
class ExportedMetricContainer2 {
 public:
  ExportedMetricContainer2();
  ~ExportedMetricContainer2();
 private:
  std::unordered_map<std::string, std::string> endpoint_;
};
```
and

```
ExportedMetricContainer2::~ExportedMetricContainer2() { }

ExportedMetricContainer2::ExportedMetricContainer2() {
  endpoint_.insert({"A", "B"});
}
```

Note: tcmalloc doesn't crash if the class `ExportedMetricContainer2` is kept in the same file.

It seems there is some `undefined behaviour` in your `redis++` library, causing tcmalloc to fail.
Note: tcmalloc is linked statically. So it is unlikely to do tcmalloc issue.

Overall program output:
```
LINE: 16
/code/eric/git/toolchain/gperftools/wrkdir/gperftools-repo/src/tcmalloc.cc:335] Attempt to free invalid pointer 0x7fff3ac9e590 
Aborted (core dumped)
```

System : Centos 7
Compiler : gcc version 5.1.0 
tcmalloc : gperftools-2.7
redis++ : commit (26f48d8)

**Comment by sewenew** [comment] 2020-09-26 04:05
@mohitmv I can not reproduce your problem. Can you remove ExporterMetricContainer related code, and only write some code to test Redis-plus-plus?

Regards

**Comment by mohitmv** [comment] 2020-09-26 11:51
Hi @sewenew , It's very indeterministic bug. Somehow the tcmalloc breaks only if the class ExporterMetricContainer is present in a separate file. It's a very trivial class in this repro.

**Comment by sewenew** [comment] 2020-09-27 14:24
@mohitmv I tried the following files:

- main.cpp: contains your main function
- exported_metric2.hpp: contains the definition of `ExportedMetricContainer2`
- exported_metric2.cpp: contains the implementation code of constructor and destructor of `ExportedMetricContainer2`

And built with the following command:

```
g++ -std=c++11 -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -I/path/to/include/files -o app main.cpp exported_metric2.cpp /path/to/libtcmalloc_minimal.a /path/to/libredis++.a /path/to/libhiredis.a
```

And the output application runs fine. No core dumped.

Please give me a minimal complete code that will definitely cause the problem, so I can compile and debug your problem.

Regards

**Comment by mohitmv** [comment] 2020-09-29 11:14
Here is the commands I used to reproduce this bug today in a directory with only 3 files:

```
  rm -f *.o redis_bug

  g++ -o redis_bug.o -c --std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -I. -I/usr/local/scaligent/toolchain/local/include redis_bug.cpp

  g++ -o exported_metric2.o -c --std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -I. -I/usr/local/scaligent/toolchain/local/include exported_metric2.cpp

  g++ -o redis_bug /usr/local/scaligent/toolchain/local/lib/libtcmalloc.a  redis_bug.o /usr/local/scaligent/toolchain/local/lib/libredis++.a /usr/local/scaligent/toolchain/local/lib/libhiredis.a exported_metric2.o 

  ./redis_bug

```
Files in my directory:

1. `redis_bug.cpp`
2. `exported_metric2.cpp`
3. `exported_metric2.hpp`

PS: We used `-D_GLIBCXX_USE_CXX11_ABI=0` flag while installing `redis++` and `tcmalloc` as well.

Content of these files is identical to what I'm pasting here:

1. `exported_metric2.hpp`

```

#ifndef COMMON_EXPORTED_METRIC2_HPP_
#define COMMON_EXPORTED_METRIC2_HPP_

#include <string>
#include <unordered_map>

namespace common {

class ExportedMetricContainer2 {
 public:
  ExportedMetricContainer2();
  ~ExportedMetricContainer2();
 private:
  std::unordered_map<std::string, std::string> endpoint_;
};

}  // namespace common

#endif  // COMMON_EXPORTED_METRIC2_HPP_

```


2. `exported_metric2.cpp`

```
#include "exported_metric2.hpp"

namespace common {

ExportedMetricContainer2::~ExportedMetricContainer2() { }

ExportedMetricContainer2::ExportedMetricContainer2() {
  endpoint_.insert({"A", "B"});
}

}  // namespace common

```

3.  `redis_bug.cpp`

```
#include <string>
#include <iostream>
#include <unordered_map>

#include "redis++/redis++.h"

#include "exported_metric2.hpp"

// This function is never called but the tcmalloc fails only if this function
// exists.
void F(sw::redis::Redis* r, const std::string& key, const std::string& field) {
  r->hget(key, field);
}

int main(int argc, char** argv) {
  std::cout << "LINE: " << __LINE__ << std::endl;
  common::ExportedMetricContainer2 c;
  (void) c;
  std::cout << "LINE: " << __LINE__ << std::endl;
  return 0;
}

```


For some very unreasonable reason, presence of  `ExportedMetricContainer2` class in a separate file (exactly how it is described above) is very important to produce this bug.

Here is the exact output:

```
LINE: 16
*** Error in `./redis_bug': munmap_chunk(): invalid pointer: 0x00007ffc9b2c61a0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7f7c4)[0x7f25d519d7c4]
./redis_bug[0x424c39]
./redis_bug[0x430a6b]
./redis_bug[0x4307ba]
./redis_bug[0x430721]
./redis_bug[0x430144]
./redis_bug[0x403682]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f25d5140505]
./redis_bug[0x403515]
======= Memory map: ========
00400000-00441000 r-xp 00000000 fd:00 28113716                           /home/genstor/thoughtspot_cpp_setup/redis_repro/redis_bug
00640000-00641000 r--p 00040000 fd:00 28113716                           /home/genstor/thoughtspot_cpp_setup/redis_repro/redis_bug
00641000-00642000 rw-p 00041000 fd:00 28113716                           /home/genstor/thoughtspot_cpp_setup/redis_repro/redis_bug
01f4a000-01f6b000 rw-p 00000000 00:00 0                                  [heap]
7f25d511e000-7f25d52e1000 r-xp 00000000 fd:00 26230692                   /usr/lib64/libc-2.17.so
7f25d52e1000-7f25d54e1000 ---p 001c3000 fd:00 26230692                   /usr/lib64/libc-2.17.so
7f25d54e1000-7f25d54e5000 r--p 001c3000 fd:00 26230692                   /usr/lib64/libc-2.17.so
7f25d54e5000-7f25d54e7000 rw-p 001c7000 fd:00 26230692                   /usr/lib64/libc-2.17.so
7f25d54e7000-7f25d54ec000 rw-p 00000000 00:00 0 
7f25d54ec000-7f25d5501000 r-xp 00000000 fd:00 26246781                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f25d5501000-7f25d5700000 ---p 00015000 fd:00 26246781                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f25d5700000-7f25d5701000 r--p 00014000 fd:00 26246781                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f25d5701000-7f25d5702000 rw-p 00015000 fd:00 26246781                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f25d5702000-7f25d5803000 r-xp 00000000 fd:00 26246198                   /usr/lib64/libm-2.17.so
7f25d5803000-7f25d5a02000 ---p 00101000 fd:00 26246198                   /usr/lib64/libm-2.17.so
7f25d5a02000-7f25d5a03000 r--p 00100000 fd:00 26246198                   /usr/lib64/libm-2.17.so
7f25d5a03000-7f25d5a04000 rw-p 00101000 fd:00 26246198                   /usr/lib64/libm-2.17.so
7f25d5a04000-7f25d5aed000 r-xp 00000000 fd:00 26246228                   /usr/lib64/libstdc++.so.6.0.19
7f25d5aed000-7f25d5cec000 ---p 000e9000 fd:00 26246228                   /usr/lib64/libstdc++.so.6.0.19
7f25d5cec000-7f25d5cf4000 r--p 000e8000 fd:00 26246228                   /usr/lib64/libstdc++.so.6.0.19
7f25d5cf4000-7f25d5cf6000 rw-p 000f0000 fd:00 26246228                   /usr/lib64/libstdc++.so.6.0.19
7f25d5cf6000-7f25d5d0b000 rw-p 00000000 00:00 0 
7f25d5d0b000-7f25d5d2d000 r-xp 00000000 fd:00 26230686                   /usr/lib64/ld-2.17.so
7f25d5f0c000-7f25d5f11000 rw-p 00000000 00:00 0 
7f25d5f29000-7f25d5f2c000 rw-p 00000000 00:00 0 
7f25d5f2c000-7f25d5f2d000 r--p 00021000 fd:00 26230686                   /usr/lib64/ld-2.17.so
7f25d5f2d000-7f25d5f2e000 rw-p 00022000 fd:00 26230686                   /usr/lib64/ld-2.17.so
7f25d5f2e000-7f25d5f2f000 rw-p 00000000 00:00 0 
7ffc9b2a8000-7ffc9b2c9000 rw-p 00000000 00:00 0                          [stack]
7ffc9b3b5000-7ffc9b3b7000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
./run.sh: line 73: 21986 Aborted                 (core dumped) ./redis_bug
```


Note that if we don't include ExportedMetricContainer then output is as expected:
```
LINE: 16
LINE: 19
```

It's quite possible that this bug is in tcmalloc.

Thanks.

**Comment by sewenew** [comment] 2020-09-30 12:34
@mohitmv Thanks for your info. However, I still cannot reproduce your problem with the following environment:

```
system: ubuntu 18.04
compiler: GCC 5.5.0
tcmalloc : gperftools-2.7
```

Since your code doesn't call anything on redis-plus-plus (the function `F` in your code has never been called), I don't think it's a problem on redis-plus-plus.

However, tcmalloc's readme file suggests [passing the following compiler options](https://github.com/gperftools/gperftools/tree/gperftools-2.7) when compiling your application:

```
-fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free
```

You can try it, maybe that caused your problem.

Regards

**Comment by sewenew** [comment] 2020-10-12 12:59
@mohitmv Since I cannot reproduce the problem, I'll close this issue. If you can give more info, or have a reproducible env, e.g. docker container, feel free to reopen it.

Regards

**Closed by sewenew** 2020-10-12 12:59 UTC
