### ISSUE TITLE
Windows 10 compilation problem

### ISSUE THREAD

**Issue by hmateoSice** [sewenew/redis-plus-plus#387] opened 2022-09-02 09:14 UTC
Hi, I have recently migrated to 1.3.5 version and I have found a compilation error, using VS17. It's related with queued_redis.hpp, and I was compiling for x86 debug.
Oh, and I have recently been trying to compile redis++ on x64 and I am having problems with the exports.def, as the symbols are not the same. Any help with it?

**Comment by sewenew** [comment] 2022-09-03 08:19
>  I have found a compilation error, using VS17.

What is the compilation error? Can you show me the error message? I don't have a Windows box near by, and cannot reproduce it. Thanks!

>  I am having problems with the exports.def, as the symbols are not the same. Any help with it?

I'm not familiar with Windows developing environment. What's exactly the problem with exports.def? Also you should ensure that both hiredis and redis-plus-plus have the same compilation settings, say, both compiled with X64 Debug, or both compiled with x86 Release, and so on.

Regards

**Comment by sewenew** [comment] 2022-09-27 14:10
Since there's no update, I'll close this issue.

Regards

**Closed by sewenew** 2022-09-27 14:10 UTC
