### ISSUE TITLE
[QUESTION] AsyncRedis::get() proper timeout

### ISSUE THREAD

**Issue by mirkub** [sewenew/redis-plus-plus#448] opened 2023-01-24 13:21 UTC
**Describe the problem**
Is it possible to configure a timeout so that the async client call (for GET) expires within this timeout? Now I set all possible timeouts to 20ms but I still see latency of 500ms of sw::redis::AsyncRedis::get() when the redis server is not behaving well (bad network/stop signal sent etc).

**Environment:**
 - OS: centos7
 - Compiler: g++ (GCC) 4.8.5
 - redis-plus-plus version: 1.3.7

**Comment by sewenew** [comment] 2023-01-25 14:43
Sorry, but I’m on vacation, and cannot reproduce your problem. Normally, You can set ConnectionOptions::socket_timeout to enable timeout when reading/ writing Redis. You can try it, if you still have problem, please give a minimum code which reproduces your problem.

Regards

________________________________
发件人: mirkub ***@***.***>
发送时间: Tuesday, January 24, 2023 9:21:20 PM
收件人: sewenew/redis-plus-plus ***@***.***>
抄送: Subscribed ***@***.***>
主题: [sewenew/redis-plus-plus] [QUESTION] (Issue #448)


Describe the problem
Is it possible to configure a timeout so that the async client call (for GET) expires within this timeout? Now I set all possible timeouts to 20ms but I still see latency of 500ms of sw::redis::AsyncRedis::get() when the redis server is not behaving well (bad network/stop signal sent etc).

Environment:

  *   OS: centos7
  *   Compiler: g++ (GCC) 4.8.5
  *   redis-plus-plus version: 1.3.7

―

**Comment by sewenew** [comment] 2023-01-28 02:59
I did some test, and the `socket_timeout` works with release 1.3.7 and the latest code on master branch. You can try the following code to have a test.

```
try {
  sw::redis::ConnectionOptions opts;
  opts.host = "127.0.0.1";
  opts.port = 6379;
  opts.socket_timeout = std::chrono::milliseconds(1);
  auto r = AsyncRedis(opts);
  cout << *(r.get("key").get()) << endl;
} catch (const TimeoutError &e) {
  // timeout
} catch (const Error &e) {
  // other errors
}
```

I'll close the issue. If you still have problem, feel free to reopen it.

Regards

**Closed by sewenew** 2023-01-28 02:59 UTC
