### ISSUE TITLE
[BUG] Online service core dumped occassionally when using pipeline to get.

### ISSUE THREAD

**Issue by zhaocc1106** [sewenew/redis-plus-plus#431] opened 2022-12-10 09:30 UTC
**Describe the bug**
My service used pipeline to get, as following codes:
```
int RedisDao::get_pipeline(const std::vector<std::string> &keys, std::vector<std::string> &results) {
  for (int i = 0; i < _max_retry; i++) {
    auto pipe = _redis->pipeline(false);
    try {
      for (const auto &key : keys) {
        pipe.get(key);
      }
      auto replies = pipe.exec();
      for (int j = 0; j < replies.size(); j++) {
        try {
          results.emplace_back(replies.get<std::string>(j));
        } catch (const sw::redis::ProtoError &e) {
          results.emplace_back("");
        }
      }
      if (results.size() != keys.size()) {
        LOG(WARNING) << "Redis get_pipeline failed, results size != keys size, results size: " << results.size()
                     << ", keys size: " << keys.size();
        throw std::runtime_error("Redis get_pipeline failed, results size != keys size");
      }
      return 0;
    } catch (const std::exception &e) {
      LOG(WARNING) << "Redis get_pipeline failed and retry, exception: " << e.what();
      continue;
    } catch (...) {
      throw;
    }
  }
  throw std::runtime_error("Redis get_pipeline failed exceed max retry.");
}
```
Service will be core dumped occassionally when running some days. The core backtrace as follows:
```
*** Aborted at 1670500260 (unix time) try "date -d @1670500260" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0xea610000000c) received by PID 12 (TID 0x7f303e7c4700) from PID 12; stack trace: ***

sw::redis::Connection::Connection(sw::redis::ConnectionOptions const&)
/root/tools/hiredis/redis-plus-plus/redis-plus-plus-1.2.1/src/sw/redis++/connection.h:158
sw::redis::Connection::reconnect()
/root/tools/hiredis/redis-plus-plus/redis-plus-plus-1.2.1/src/sw/redis++/connection.cpp:380
sw::redis::QueuedRedis<sw::redis::PipelineImpl>::~QueuedRedis()
/usr/local/include/sw/redis++/queued_redis.hpp:203
src/dao/redis_dao.cc:138 (discriminator 7)
```
redis_dao.cc:138 is code line: ``} catch (const std::exception &e) {``

Is it a bug or my codes is illegal?

**To Reproduce**
Codes as above. Service run some days.

**Expected behavior**
No core dump.

**Environment:**
 - OS: ubuntu
 - Compiler: Ubuntu 7.5.0-3ubuntu1~18.04
 - hiredis version: 1.0.2
 - redis-plus-plus version: 1.2.1

**Additional context**

**Comment by sewenew** [comment] 2022-12-11 02:57
Your problem seems to be a duplicate of #172 

Please update your redis-plus-plus version to the latest release, or even better to the master branch (which fixed some async interface bugs). And try again.

Regards

**Comment by zhaocc1106** [comment] 2022-12-11 03:16
> Your problem seems to be a duplicate of #172
> 
> Please update your redis-plus-plus version to the latest release, or even better to the master branch (which fixed some async interface bugs). And try again.
> 
> Regards

I will try, thanks.

**Comment by sewenew** [comment] 2022-12-29 14:01
Since there's no update, I'll close this issue.

Regards

**Closed by sewenew** 2022-12-29 14:01 UTC
